version: '3.7'

services:
  ds_model:
    build:
      context: ../ds_model
    ports:
      - '8100:8100'
  backend:
    build:
      context: ../backend
    restart: always
    volumes:
      - static_value:/yapack/static/
      - media_value:/yapack/media/
    env_file:
      - .env
    depends_on:
      - ds_model
  frontend:
    build:
      context: ../frontend
    volumes:
      - ../frontend:/app/result_build
    depends_on:
      - backend
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
    restart: always
    depends_on:
      - frontend

volumes:
  static_value:
  media_value:
  