# Generated by Django 3.2 on 2023-06-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('packer_num', models.CharField(max_length=15, unique=True, verbose_name='Номер упаковщика')),
            ],
            options={
                'verbose_name': 'Упаковщик',
                'verbose_name_plural': 'Упаковщики',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
