# Generated by Django 2.2.16 on 2023-06-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('packer_num', models.CharField(max_length=15, unique=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Упаковщик',
                'verbose_name_plural': 'Упаковщики',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
