# Generated by Django 4.2.2 on 2023-06-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230605_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packer',
            name='packer_num',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер упаковщика'),
        ),
    ]
