# Generated by Django 3.2 on 2023-06-10 19:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargotype_id', models.IntegerField(db_index=True, help_text='id карготипа', unique=True, verbose_name='id карготипа')),
                ('description', models.CharField(db_index=True, help_text='Описание', max_length=200, unique=True, verbose_name='Описание карготипа')),
            ],
            options={
                'verbose_name': 'Карготип',
                'verbose_name_plural': 'Карготипы',
                'ordering': ['cargotype_id'],
            },
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, unique=True, verbose_name='Название типа упаковки.')),
                ('length', models.FloatField(help_text='Длина товара', validators=[django.core.validators.MinValueValidator(0.0, message='Размер не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Размер не может быть больше 10000')], verbose_name='Длина')),
                ('width', models.FloatField(help_text='Ширина товара', validators=[django.core.validators.MinValueValidator(0.0, message='Размер не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Размер не может быть больше 10000')], verbose_name='Ширина')),
                ('height', models.FloatField(help_text='Высота товара', validators=[django.core.validators.MinValueValidator(0.0, message='Размер не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Размер не может быть больше 10000')], verbose_name='Высота')),
                ('price', models.FloatField(help_text='Цена товара', null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Цена не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Цена не может быть больше 10000')], verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_key', models.CharField(db_index=True, help_text='id заказа', max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='id заказа')),
                ('suggested_carton_match', models.BooleanField(null=True, verbose_name='Совпадение используемой и предложенной упаковки')),
                ('packman_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.packer', verbose_name='Упаковщик')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('sku_number', models.CharField(help_text='id товара', max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='id товара')),
                ('dimension_a', models.FloatField(blank=True, help_text='Размер товара a', null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Размер не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Размер не может быть больше 10000')], verbose_name='Размер a')),
                ('dimension_b', models.FloatField(blank=True, help_text='Размер товара b', null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Размер не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Размер не может быть больше 10000')], verbose_name='Размер b')),
                ('dimension_c', models.FloatField(blank=True, help_text='Размер товара c', null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Размер не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Размер не может быть больше 10000')], verbose_name='Размер c')),
                ('sku_wght', models.FloatField(blank=True, help_text='Вес товара', null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Вес не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Вес не может быть больше 10000')], verbose_name='Вес')),
                ('cargotypes', models.ManyToManyField(blank=True, help_text='Карготипы', related_name='sku', to='orders.Cargotype', verbose_name='Карготипы')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'Номенклатура',
                'ordering': ['sku_number'],
            },
        ),
        migrations.CreateModel(
            name='SkuInOrderAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Количество', validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть меньше 1')], verbose_name='Количество SKU')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sku', verbose_name='ID товара')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCartonInOrderAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Количество', validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть меньше 1')], verbose_name='Количество использованной упаковки в заказе')),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.carton', verbose_name='ID товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedCartonInOrderAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Количество', validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть меньше 1')], verbose_name='Количество рекомендованной упаковки в заказе')),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.carton', verbose_name='ID товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='recommended_carton',
            field=models.ManyToManyField(related_name='recommended_carton', through='orders.RecommendedCartonInOrderAmount', to='orders.Carton', verbose_name='Рекомендуемая упаковка'),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_carton',
            field=models.ManyToManyField(related_name='selected_carton', through='orders.SelectedCartonInOrderAmount', to='orders.Carton', verbose_name='Использованная упаковка'),
        ),
        migrations.AddField(
            model_name='order',
            name='sku_list',
            field=models.ManyToManyField(blank=True, through='orders.SkuInOrderAmount', to='orders.Sku', verbose_name='SKU'),
        ),
    ]
