# Generated by Django 3.2 on 2023-06-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuCargotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cargotype', verbose_name='карготип')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sku', verbose_name='ID товара')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'Карготипы товаров',
            },
        ),
    ]
