# Generated by Django 4.2.2 on 2023-06-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='suggested_carton_match',
            field=models.BooleanField(default=False, verbose_name='Совпадение используемой и предложенной упаковки'),
        ),
    ]
