# Generated by Django 2.2.16 on 2023-06-08 15:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_packer_packer_num'),
        ('orders', '0002_order_suggested_carton_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='id заказа')),
                ('package_match', models.BooleanField(default=False, verbose_name='Совпадение предложенной и использованной упаковки')),
                ('packer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Packer', verbose_name='Упаковщик')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReceivedSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(verbose_name='Количество')),
                ('order_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='orders.OrderReceived', verbose_name='Заказ')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.Sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'SKU в заказе',
                'verbose_name_plural': 'SKU в заказе',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagetype', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Тип упаковки')),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Размер не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Размер не может быть больше 10000')], verbose_name='Длина')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Размер не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Размер не может быть больше 10000')], verbose_name='Ширина')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Размер не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Размер не может быть больше 10000')], verbose_name='Высота')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Цена не может быть меньше нуля'), django.core.validators.MaxValueValidator(10000.0, message='Цена не может быть больше 10000')], verbose_name='Цена')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='packman_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recommended_carton',
        ),
        migrations.RemoveField(
            model_name='order',
            name='selected_carton',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sku',
        ),
        migrations.DeleteModel(
            name='Carton',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='skus',
            field=models.ManyToManyField(related_name='orderreceived', through='orders.OrderReceivedSku', to='orders.Sku', verbose_name='SKU в заказе'),
        ),
    ]
