# Generated by Django 2.2.16 on 2023-06-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230608_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRecommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='orders.OrderReceived', verbose_name='Заказ')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomended', to='orders.Package', verbose_name='Рекомендованная упаковка')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed', to='orders.Sku', verbose_name='Рекомендованная упаковка')),
            ],
            options={
                'verbose_name': 'Рекомендованная упаковка',
                'verbose_name_plural': 'Рекомендованнае упаковки',
                'ordering': ['order', 'package'],
            },
        ),
    ]
