# Generated by Django 2.2.16 on 2023-06-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20230608_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagerecommended',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed', to='orders.Sku', verbose_name='SKU'),
        ),
    ]
