# Generated by Django 2.2.16 on 2023-06-09 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20230608_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='barcode',
            field=models.CharField(default=0, max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13, message='Штрихкод не может быть короче 13-ти символов')], verbose_name='Штрихкод'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='barcode',
            field=models.CharField(default=0, max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13, message='Штрихкод не может быть короче 13-ти символов')], verbose_name='Штрихкод'),
            preserve_default=False,
        ),
    ]
