# Generated by Django 2.2.16 on 2023-06-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20230612_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargotype',
            name='description',
            field=models.CharField(help_text='Описание', max_length=200, verbose_name='Описание карготипа'),
        ),
    ]
