# Generated by Django 3.2 on 2023-06-12 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_packer_packer_num'),
        ('orders', '0009_auto_20230612_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagerecommended',
            name='sku',
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='packer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.packer', verbose_name='Упаковщик'),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='skus',
            field=models.ManyToManyField(through='orders.OrderReceivedSku', to='orders.Sku', verbose_name='SKU в заказе'),
        ),
        migrations.AlterField(
            model_name='orderreceivedsku',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderreceived', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderreceivedsku',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.sku', verbose_name='SKU'),
        ),
    ]
