# Generated by Django 3.2 on 2023-06-13 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20230613_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagerecommended',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='orders.orderreceived', verbose_name='Заказ'),
        ),
    ]
