# Generated by Django 3.2 on 2023-06-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_packagerecommended_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='status',
            field=models.CharField(choices=[('no_rec', 'no_rec'), ('in_work', 'in_work'), ('ready', 'ready')], default='no_rec', max_length=7),
        ),
    ]
