# Generated by Django 3.2 on 2023-06-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderreceived_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceivedsku',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.sku', verbose_name='SKU'),
        ),
    ]
