# Generated by Django 3.2 on 2023-06-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_packageselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageselected',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_sel', to='orders.orderreceived', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='packageselected',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.package', verbose_name='Выбранная упаковка'),
        ),
    ]
