# Generated by Django 3.2 on 2023-06-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_packageselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='problem_discription',
            field=models.CharField(blank=True, default='no ploblem', max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='status',
            field=models.CharField(choices=[('no_rec', 'no_rec'), ('in_work', 'in_work'), ('ready', 'ready'), ('problem', 'problem')], default='no_rec', max_length=7),
        ),
        migrations.AlterField(
            model_name='packageselected',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_sel', to='orders.orderreceived', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='packageselected',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.package', verbose_name='Выбранная упаковка'),
        ),
    ]
