# Generated by Django 3.2 on 2023-06-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20230617_1845'),
        ('orders', '0016_auto_20230618_0042'),
    ]

    operations = [
    ]
