// const products = [
//   "Смартфон Apple iPhone 12 Pro Max 256GB",
//   "Ноутбук Lenovo ThinkPad X1 Carbon 9th Gen",
//   "Телевизор Samsung QLED Q80T 65 дюймов",
//   "Кофемашина De'Longhi Magnifica S ECAM 22.110.B",
//   "Пылесос Dyson V11 Absolute Extra Pro",
//   "Акустическая система JBL Charge 4 Portable Bluetooth Speaker",
//   "Игровая приставка PlayStation 5 с дополнительным контроллером DualSense",
//   "Умные часы Apple Watch Series 6 GPS + Cellular 44mm",
//   "Фотоаппарат Canon EOS 5D Mark IV с объективом Canon EF 24-105mm f/4L IS II USM",
//   "Планшет Samsung Galaxy Tab S7 Plus 12.4 дюйма 256GB",
//   "Кухонный комбайн Bosch MUM4405 Styline",
//   "Электрический чайник Philips HD9350/90 Avance Collection",
//   "Мультиварка Redmond RMC-M4502E multicooker 5 литров",
//   "Холодильник LG InstaView Door-in-Door GC-X247CQBV",
//   "Микроволновая печь Samsung MG23K3575AK/UR с грилем",
//   "Смарт-телевизор LG OLED65CX9LA 65 дюймов",
//   "Утюг Tefal FV5648 Ultimate Pure Anti Scale",
//   "Bluetooth-наушники Sony WH-1000XM4 с технологией шумоподавления",
//   "Автомобильный видеорегистратор Xiaomi 70mai A800 Dual Dash Cam",
//   "Беспроводные наушники Apple AirPods Pro с активным шумоподавлением",
//   "Монитор Dell UltraSharp U2719D 27 дюймов",
//   "Фитнес-браслет Xiaomi Mi Band 6 с AMOLED-экраном",
//   "Видеокамера GoPro HERO9 Black с функцией съемки 5K",
//   "Смарт-колонка Amazon Echo Dot (4th Gen) с голосовым помощником Alexa",
//   "Электрическая зубная щетка Oral-B Pro 2 2500N CrossAction",
//   "Умные весы Xiaomi Mi Body Composition Scale 2 с анализом данных",
//   "Смарт-часы Samsung Galaxy Watch 3 45mm с функцией измерения пульса",
//   "Геймпад Xbox Wireless Controller для Xbox Series X|S и Xbox One",
//   "Блендер Bosch VitaStyle Mixx2Go MMBM7G4M",
//   "Умный домкрат Xiaomi 70mai Smart Electric Jack",
//   "Электрическая бритва Philips Series 9000 Prestige SP9863/16",
//   "Массажное кресло JSB MZ21 Power Compact Full Body Massage Chair",
//   "Камера наблюдения Arlo Pro 4 2K с аккумулятором",
//   "Электрический скейт Razor X Cruiser Electric Skateboard",
//   "Умный светильник Philips Hue Play Gradient Lightstrip",
//   "Универсальный пульт Logitech Harmony Elite с технологией управления",
//   "Дрель-шуруповерт Bosch GSR 12V-15 2x2.0Ah ProCORE",
//   "Смарт-термометр Withings Thermo с Wi-Fi и Bluetooth",
//   "Робот-пылесос iRobot Roomba i7+ с автоматической очисткой",
//   "Умная кофемашина Nespresso Expert&Milk с возможностью приготовления разных напитков",
//   "Воздухоочиститель Xiaomi Mi Air Purifier 3H с фильтрацией воздуха",
//   "Умный замок August Wi-Fi Smart Lock с функцией удаленного управления",
//   "Игровой набор LEGO Star Wars Imperial Star Destroyer 75252 Ultimate Collector Series",
//   "Плюшевый медведь 50 см с мягким мехом и пушистыми лапками",
//   "Пазл Ravensburger 'Звездная ночь' с 5000 элементов",
//   "Столовый сервиз 'Фарфоровая Роза' из 60 предметов",
//   "Картина на холсте 'Абстракция в синем' размером 120x80 см",
//   "Декоративная подушка 'Желтый геометрический узор' 45x45 см",
//   "Сковорода Tefal Talent Pro с антипригарным покрытием и съемной ручкой",
//   "Плед из мягкого флиса размером 150x200 см",
//   "Деревянная игрушка 'Конструктор' с элементами разных цветов и форм",
//   "Набор посуды Luminarc 'Париж' из 12 предметов",
//   "Стеклянный ваза в стиле лофт с оригинальным дизайном",
//   "Настольная игра 'Кодовое имя' с карточками и инструкцией",
//   "Керамический горшок для растений с отверстием для стока воды",
//   "Плюшевый единорог 30 см с радужной гривой и мягкой текстурой",
//   "Фоторамка 'Семейные воспоминания' из дерева с возможностью подвешивания",
//   "Магнитная доска для записей с маркерами и стирающей губкой",
//   "Пазл 1000 элементов 'Пейзаж на озере' с яркой и детализированной картинкой",
//   "Ароматическая свеча в стеклянном сосуде с запахом ванили и корицы",
//   "Коврик для йоги 'Мандала' с антискользящим покрытием и удобной толщиной",
//   "Магниты для холодильника 'Города мира' с изображениями известных достопримечательностей",
//   "Детский конструктор 'Робот Трансформер' с возможностью собрать несколько моделей",
// ];

// export default products;
